name: start
version: 0.7.0
homepage: http://github.com/priezz/start
description: Sinatra inspired Web framework
environment:
  sdk: '>=2.2.0 <3.0.0'
dependencies:
  http_server: ^0.9.8+3
  http: ^0.12.0+4
  mime: ^0.9.6+3

dev_dependencies:
  test: '>=1.9.4 <2.0.0'
  mockito: ^4.1.1
