name: start
version: 0.8.0
homepage: http://github.com/priezz/start
description: Sinatra inspired Web framework
environment:
  sdk: ">=2.11.0 <3.0.0"
dependencies:
  http: ^0.13.0
  http_parser: ^4.0.0
  mime: ^1.0.0
  shelf: ^1.0.0

dev_dependencies:
  test: ^1.16.0-nullsafety.9
  mockito: ^4.1.4
