name: start
version: 0.8.1
homepage: http://github.com/priezz/start
description: Sinatra inspired Web framework
environment:
  sdk: ">=2.11.0 <3.0.0"
dependencies:
  http: ^0.13.0
  mime: ^1.0.0
  # shelf: ^1.0.0

dev_dependencies:
  test: ^1.16.4
  mockito: ^5.0.0

# dependency_overrides:
#   http_parser: ^4.0.0
#   shelf: ^1.0.0
